import Head from 'next/head';
import Link from 'next/link';
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>HomePage</h1>

      <p className={styles.text}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Autem, vel saepe quaerat laudantium numquam reprehenderit explicabo!
      </p>
      <p className={styles.text}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Autem, vel saepe quaerat laudantium numquam reprehenderit explicabo!
      </p>
      <p className={styles.text}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Autem, vel saepe quaerat laudantium numquam reprehenderit explicabo!
      </p>

      <Link href="/ninjas">
        <a className={styles.btn}>
          See Ninja Listing
        </a>
      </Link>
    </div>
  );
};
